name: Sync with Repository B

on:
  push:
    branches:
      - main
    # You can include additional branches as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository A
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Git config
        run: |
          git config user.email "agatevureglory@gmail.com"
          git config user.name "gconnect"

      - name: Add Repository B as a remote
        run: |
          git remote add https://github.com/gconnect/Thirdspace.git
          git fetch https://github.com/gconnect/Thirdspace.git

      - name: Merge changes from Repository A to Repository B
        run: |
          git checkout main # Use the branch you want to sync with (main or dev)
          git pull https://github.com/gconnect/Thirdspace.git main --ff-only

      - name: Push changes to Repository B
        run: |
          git push https://github.com/gconnect/Thirdspace.git main # Use the branch you want to sync with (main or dev)

      - name: Clean up
        run: |
          git remote remove https://github.com/gconnect/Thirdspace.git
